properties:


  - name: inventory_index
    type: AllegroFlare::InventoryIndex
    init_with: '{}'
    constructor_arg: true
    getter: true
    getter_ref: true
    setter: true

  - name: af_inventory
    type: AllegroFlare::Inventory
    init_with: '{}'
    constructor_arg: true
    getter: true
    getter_ref: true
    setter: true

  - name: flags
    type: AllegroFlare::Inventory
    init_with: '{}'
    constructor_arg: true
    getter: true
    getter_ref: true
    setter: true

  - name: entity_dictionary
    type: std::map<std::string, AllegroFlare::Prototypes::FixedRoom2D::Entities::Base*>
    init_with: '{}'
    constructor_arg: true
    getter: true
    getter_ref: true
    setter: true

  - name: room_dictionary
    type: std::map<std::string, AllegroFlare::Prototypes::FixedRoom2D::Room*>
    init_with: '{}'
    constructor_arg: true
    getter: true
    getter_ref: true
    setter: true

  - name: entity_room_associations
    type: std::map<std::string, std::string>
    init_with: '{}'
    constructor_arg: true
    getter: true
    getter_ref: true
    setter: true

  - name: script_dictionary
    type: std::map<std::string, AllegroFlare::Prototypes::FixedRoom2D::Script>
    init_with: '{}'
    constructor_arg: true
    getter: true
    getter_ref: true
    setter: true

  - name: starting_room_identifier
    type: std::string
    init_with: '"[unset-starting_room_identifier]"'
    getter: true
    setter: true
    getter_ref: true


dependencies:


  - symbol: AllegroFlare::Inventory
    headers: [ AllegroFlare/Inventory.hpp ]
  - symbol: AllegroFlare::InventoryIndex
    headers: [ AllegroFlare/InventoryIndex.hpp ]
  - symbol: AllegroFlare::Prototypes::FixedRoom2D::Entities::Base
    headers: [ AllegroFlare/Prototypes/FixedRoom2D/Entities/Base.hpp ]
  - symbol: AllegroFlare::Prototypes::FixedRoom2D::Room
    headers: [ AllegroFlare/Prototypes/FixedRoom2D/Room.hpp ]
  - symbol: AllegroFlare::Prototypes::FixedRoom2D::Script
    headers: [ AllegroFlare/Prototypes/FixedRoom2D/Script.hpp ]


