#pragma once

#define ALLEGRO_FLARE_EVENT_PROGRAM_START               ALLEGRO_GET_EVENT_TYPE('F','P','g','S')
#define ALLEGRO_FLARE_EVENT_SHUTDOWN_PROGRAM            ALLEGRO_GET_EVENT_TYPE('F','S','d','n')
#define ALLEGRO_FLARE_EVENT_OFFSET_PRIMARY_TIMER        ALLEGRO_GET_EVENT_TYPE('F','O','P','T')
#define ALLEGRO_FLARE_EVENT_EXIT_GAME                   ALLEGRO_GET_EVENT_TYPE('F','E','x','t')
#define ALLEGRO_FLARE_EVENT_START_NEW_GAME              ALLEGRO_GET_EVENT_TYPE('F','S','t','r')
#define ALLEGRO_FLARE_EVENT_SELECT_LEVEL                ALLEGRO_GET_EVENT_TYPE('F','S','l','l')
#define ALLEGRO_FLARE_EVENT_START_TITLE_SCREEN          ALLEGRO_GET_EVENT_TYPE('F','T','t','l')
#define ALLEGRO_FLARE_EVENT_GAME_WON                    ALLEGRO_GET_EVENT_TYPE('F','G','m','w')
#define ALLEGRO_FLARE_EVENT_CONTINUE_GAME               ALLEGRO_GET_EVENT_TYPE('F','C','t','n')
#define ALLEGRO_FLARE_EVENT_PAUSE_GAME                  ALLEGRO_GET_EVENT_TYPE('F','P','w','s')
#define ALLEGRO_FLARE_EVENT_UNPAUSE_GAME                ALLEGRO_GET_EVENT_TYPE('F','U','n','p')
#define ALLEGRO_FLARE_EVENT_PLAY_MUSIC_TRACK            ALLEGRO_GET_EVENT_TYPE('F','S','t','m')
#define ALLEGRO_FLARE_EVENT_PLAY_SOUND_EFFECT           ALLEGRO_GET_EVENT_TYPE('F','P','s','f')
#define ALLEGRO_FLARE_EVENT_STOP_ALL_MUSIC_TRACKS       ALLEGRO_GET_EVENT_TYPE('F','S','A','M')
#define ALLEGRO_FLARE_EVENT_VIRTUAL_CONTROL_BUTTON_DOWN ALLEGRO_GET_EVENT_TYPE('F','V','b','d')
#define ALLEGRO_FLARE_EVENT_VIRTUAL_CONTROL_BUTTON_UP   ALLEGRO_GET_EVENT_TYPE('F','V','b','u')
#define ALLEGRO_FLARE_EVENT_VIRTUAL_CONTROL_AXIS_CHANGE ALLEGRO_GET_EVENT_TYPE('F','V','a','c')
#define ALLEGRO_FLARE_EVENT_UNLOCK_ACHIEVEMENT          ALLEGRO_GET_EVENT_TYPE('F','U','l','A')
#define ALLEGRO_FLARE_EVENT_ACHIEVEMENT_UNLOCKED        ALLEGRO_GET_EVENT_TYPE('F','A','c','U')
#define ALLEGRO_FLARE_EVENT_SWITCH_SCREEN               ALLEGRO_GET_EVENT_TYPE('F','s','m','s')
#define ALLEGRO_FLARE_EVENT_ROUTER                      ALLEGRO_GET_EVENT_TYPE('F','R','t','r')
#define ALLEGRO_FLARE_EVENT_TOGGLE_FULLSCREEN           ALLEGRO_GET_EVENT_TYPE('F','T','g','F')
#define ALLEGRO_FLARE_EVENT_DISABLE_FULLSCREEN          ALLEGRO_GET_EVENT_TYPE('F','D','s','F')
#define ALLEGRO_FLARE_EVENT_ENABLE_FULLSCREEN           ALLEGRO_GET_EVENT_TYPE('F','E','n','F')


// Notices

//#define ALLEGRO_FLARE_EVENT_SCREEN_ACTIVATED            ALLEGRO_GET_EVENT_TYPE('F','S','A','c')
//#define ALLEGRO_FLARE_EVENT_SCREEN_DEACTIVATED          ALLEGRO_GET_EVENT_TYPE('F','S','D','a')


// likely to only be internal

#define ALLEGRO_FLARE_EVENT_SHOW_INPUT_HINTS_BAR                    ALLEGRO_GET_EVENT_TYPE('F','S','I','H')
#define ALLEGRO_FLARE_EVENT_HIDE_INPUT_HINTS_BAR                    ALLEGRO_GET_EVENT_TYPE('F','H','i','I')
#define ALLEGRO_FLARE_EVENT_SET_INPUT_HINTS_BAR                     ALLEGRO_GET_EVENT_TYPE('F','S','h','I')
#define ALLEGRO_FLARE_EVENT_SET_INPUT_HINTS_BAR_TEXT_OPACITY        ALLEGRO_GET_EVENT_TYPE('F','S','n','t')
#define ALLEGRO_FLARE_EVENT_SET_INPUT_HINTS_BAR_BACKFILL_OPACITY    ALLEGRO_GET_EVENT_TYPE('F','S','b','o')
#define ALLEGRO_FLARE_EVENT_SET_INPUT_HINTS_BAR_HEIGHT              ALLEGRO_GET_EVENT_TYPE('F','S','I','h')
#define ALLEGRO_FLARE_EVENT_POST_ACHIEVEMENT_UNLOCKED_NOTIFICATION  ALLEGRO_GET_EVENT_TYPE('F','P','s','N')
#define ALLEGRO_FLARE_EVENT_HOTLOAD_SHADER_SOURCE                   ALLEGRO_GET_EVENT_TYPE('F','H','l','S')
#define ALLEGRO_FLARE_EVENT_SET_SHADER_TARGET_FOR_HOTLOADING        ALLEGRO_GET_EVENT_TYPE('F','S','H','S')
#define ALLEGRO_FLARE_EVENT_POLL_HOTLOAD_SHADER_SOURCE_FOR_CHANGE   ALLEGRO_GET_EVENT_TYPE('F','P','H','S')

// Not sure the exact roles of OPEN, CLOSE, SWITCH_IN, and SWITCH_OUT
#define ALLEGRO_FLARE_EVENT_DIALOG                                  ALLEGRO_GET_EVENT_TYPE('F','D','l','g')
#define ALLEGRO_FLARE_EVENT_DIALOG_OPEN                             ALLEGRO_GET_EVENT_TYPE('F','D','O','p')
#define ALLEGRO_FLARE_EVENT_DIALOG_ADVANCE                          ALLEGRO_GET_EVENT_TYPE('F','D','A','v')
#define ALLEGRO_FLARE_EVENT_DIALOG_CLOSE                            ALLEGRO_GET_EVENT_TYPE('F','D','C','l')
#define ALLEGRO_FLARE_EVENT_DIALOG_SWITCHED_IN                      ALLEGRO_GET_EVENT_TYPE('F','D','S','I')
#define ALLEGRO_FLARE_EVENT_DIALOG_SWITCHED_OUT                     ALLEGRO_GET_EVENT_TYPE('F','D','S','O')


#define ALLEGRO_FLARE_EVENT_DIALOG_SWITCH_IN_NAME                   "dialog_switched_in"
#define ALLEGRO_FLARE_EVENT_DIALOG_SWITCH_OUT_NAME                  "dialog_switched_out"

// User's Events in their game
#define ALLEGRO_FLARE_EVENT_GAME_EVENT                  ALLEGRO_GET_EVENT_TYPE('F','E','G','E')

// Consider:
// { 
//    std::string event_identifier
//    intptr_t allegro_event
// }

// Also Consider:
// ALLEGRO_FLARE_EVENT_INCREMENT_PLAYER_STAT


