#ifndef __AF_CONSOLE_COLOR_HEADER
#define __AF_CONSOLE_COLOR_HEADER




#define CONSOLE_COLOR_RED "\033[1;31m"
#define CONSOLE_COLOR_YELLOW "\033[1;33m"
#define CONSOLE_COLOR_GREEN "\033[1;32m"
#define CONSOLE_COLOR_DEFAULT "\033[0m"




#endif
